# Generated by Django 3.2.9 on 2021-11-23 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211123_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 23, 20, 19, 46, 902442)),
        ),
    ]
