# Generated by Django 3.2.9 on 2021-11-23 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211123_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 23, 22, 27, 36, 960582)),
        ),
    ]
